### ISSUE TITLE
Enact 2.0 Roadmap

### ISSUE THREAD

**Issue by webOS101** [enactjs/enact#1504]
The focus of the 2.0 release is a generalization of the components built within 1.x to enable us to create new experiences for other platforms beyond the 10 foot experience. We also want to improve the overall developer experience of using Enact

### Features

- [x] Expanding `@enact/ui` to provide generalized, unstyled base components on which we can build themed versions for difference experiences
- [x] Expand and improve our developer tooling provided by `@enact/cli`
- [x] Add touch and gesture support
- [ ] Add multi-platform support beyond webOS
- [x] Add components to support webOS digital signage products
- [x] Add support for voice control of components

### Quality

- [x] Improve the integration of `@enact/i18n` with `@enact/moonstone` by supporting asynchronous retrieval of internationalization resources
- [x] Improve component-level render and update performance across the framework
- [x] Revisit our unit test architecture to provide better coverage and faster run times

**Comment by elijahdorman** [comment]
Is there any plan to add support for the Pointer API? It now has native support on every browser except Safari and has a good polyfill for that case. Seems like a more forward-looking solution than "touch support".

[Polyfill](https://github.com/jquery/PEP)

[Can I Use](https://caniuse.com/#feat=pointer)

**Comment by ryanjduffy** [comment]
@elijahdorman Thanks for the feedback! I agree that pointer events support needs to be part of our roadmap. We're somewhat constrained right now because our current generation of webOS platform does not yet support pointer events. That said, it would be worth investigating how a polyfill would work with our existing [work-in-progress support](https://github.com/enactjs/enact/tree/develop/packages/ui/Touchable/Touchable.js). Appreciate the idea!

**Comment by nghiatv** [comment]
Does Enact 2 support full webOS 4 SDK?

**Comment by webOS101** [comment]
@nghiatv You can see which API's are exposed natively in the `webos` module [here](https://github.com/enactjs/enact/tree/develop/packages/webos).  Any other API's can be access through `LS2Request`.

**Comment by ryanjduffy** [comment]
I've updated the roadmap to reflect the work included in the 2.0.0 release of Enact. One feature and two quality improvements were not built for 2.0.0 but are still on our near term roadmap so remain here.

We're in the midst of 2.x planning now so we're open to feedback from the community on what they'd like to see added and improved in Enact. Once we have some initial plans on features and which minor release they will land, we'll update this post.

**Comment by webOS101** [comment]
We've moved on to 3.x development and accomplished the goals we set out to.  Closing this out.
